// Code generated by MockGen. DO NOT EDIT.
// Source: ./ec2_factory.go

// Package client is a generated GoMock package.
package client

import (
	reflect "reflect"

	aws "github.com/aws/aws-sdk-go-v2/aws"
	gomock "github.com/golang/mock/gomock"
)

// MockEC2Creator is a mock of EC2Creator interface.
type MockEC2Creator struct {
	ctrl     *gomock.Controller
	recorder *MockEC2CreatorMockRecorder
}

// MockEC2CreatorMockRecorder is the mock recorder for MockEC2Creator.
type MockEC2CreatorMockRecorder struct {
	mock *MockEC2Creator
}

// NewMockEC2Creator creates a new mock instance.
func NewMockEC2Creator(ctrl *gomock.Controller) *MockEC2Creator {
	mock := &MockEC2Creator{ctrl: ctrl}
	mock.recorder = &MockEC2CreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEC2Creator) EXPECT() *MockEC2CreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockEC2Creator) Create(config aws.Config) EC2Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", config)
	ret0, _ := ret[0].(EC2Client)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEC2CreatorMockRecorder) Create(config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEC2Creator)(nil).Create), config)
}
